---
- name: Update and Install PHP
  hosts: parent

  pre_tasks:
  
  - name: Updating servers
    tags: always
    package:
      update_cache: yes
      state: latest

  - name: Installing PHP
    tags: install_php
    package:
      name: "{{ php }}"
      state: latest


- name: Install and Start Apache on CentOS servers
  hosts: centos

  tasks:

  - name: Installing Apache
    tags: install_apache_centos
    package:
      name: "{{ apache }}"
      state: latest

  - name: Starting Apache
    tags: start_apache
    service:
      name: "{{ apache }}"
      state: started
      enabled: yes


- name: Install and Start NGINX on Webservers
  hosts: webservers

  tasks:

  - name: Installing NGINX
    tags: install_nginx
    package:
      name: nginx
      state: present

  - name: Start NGINX
    tags: start_nginx
    service:
      name: nginx
      state: started
